name: ci

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  lint:
    uses: nickatnight/gha-workflows/.github/workflows/pre-commit.yml@main

  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      # - name: Test docs build
      #   run: make sphinx

      - name: Run mypy
        run: make mypy

      - name: Run coverage
        run: uv run pytest --cov-report=xml:coverage.xml --cov=fastapi_resume/ tests/

      - name: Codecov
        if: success()
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: unittests-py${{ matrix.python-version }}
